# 基础镜像
FROM redis
# author
MAINTAINER shinetech

# 挂载目录
VOLUME /home/shinetech/redis
# 创建目录
RUN mkdir -p /home/shinetech/redis
# 指定路径
WORKDIR /home/shinetech/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/shinetech/redis/redis.conf
