# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER shinetech

# 挂载目录
VOLUME /home/shinetech
# 创建目录
RUN mkdir -p /home/shinetech
# 指定路径
WORKDIR /home/shinetech
# 复制jar文件到路径
COPY ./jar/shinetech-modules-system.jar /home/shinetech/shinetech-modules-system.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","shinetech-modules-system.jar"]