# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER shinetech

# 挂载目录
VOLUME /home/shinetech
# 创建目录
RUN mkdir -p /home/shinetech
# 指定路径
WORKDIR /home/shinetech
# 复制jar文件到路径
COPY ./jar/shinetech-auth.jar /home/shinetech/shinetech-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","shinetech-auth.jar"]